services:
  frontend:
    build: .
    container_name: casino-frontend
    restart: always
    ports:
      - "80:8080"
    environment:
      - BACKEND_HOST=backend
    networks:
      - casino-network

networks:
  casino-network:
    external: true
    name: casino-network
